#!/usr/bin/env python
# Model object casino.
# fisherds@gmail.com (Dave Fisher)

from google.appengine.api import memcache
from google.appengine.api import users
from google.appengine.ext import db
import logging

# Holds the meta data representing a single casino.
#   Entities will be children of a Trip entity.
#   Id will be autogenerated
class Casino(db.Model):
	name = db.StringProperty(required=True)
	location = db.GeoPtProperty()