// This file was autogenerated by /Users/fisherds/Documents/Google/AppEngine/elevate300/uncompiled/../../../closure/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../AppEngine/elevate300/uncompiled/js/transaction.js', ['elevate300.Transaction'], ['goog.dom', 'goog.events']);
